### PR TITLE
adding working (mostly) MoNA impl and requested changes

### PR DESCRIPTION
**Pull request by berlinguyinca**
please merge, most of your changes have been done and the MoNA imp is around 70% done now, only compound/annotion info is missing and a decent query builder.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hi Gert,

Thanks a lot! I merged the pull request. 

A few additional comments - these are mostly bureaucratic issues but since this is a collaborative project we should maintain some standard.

- Please make sure to add the copyright header to all source files. This is to prevent problems in the future.

- Please maintain the code style as described in the README. Especially, let's write JavaDoc comments as full sentences starting with a capital letter and ending with a period. 

- Please move your classes to io.github.msdk package, unless you have specific licensing/distribution plans for the MSDK code.

**Comment by tomas-pluskal** [comment]
Another topic for consideration: I think if we create a new maven project for each MSDK module, we will end up having too many maven projects with lots of maintenance overhead. My idea is to create a maven project for each group of functions, e.g.
msdk-io for data reading/writing modules
msdk-featuredetection for feature detection algoritms
msdk-identification for identification algorithms

In that sense, the msdk-mona and msdk-query could be moved to msdk-identification. What do you think?

**Comment by berlinguyinca** [comment]
please see below

On Wed, Apr 8, 2015 at 7:18 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> Hi Gert,
>
> Thanks a lot! I merged the pull request.
>
> A few additional comments - these are mostly bureaucratic issues but since
> this is a collaborative project we should maintain some standard.
>
>    -
>
>    Please make sure to add the copyright header to all source files. This
>    is to prevent problems in the future.
>
> good point

>
>    -
>
>    Please maintain the code style as described in the README. Especially,
>    let's write JavaDoc comments as full sentences starting with a capital
>    letter and ending with a period.
>
> yes, I check it out and will try to adhere to it

>
>    -
>
>     -
>
>    Please move your classes to io.github.msdk package, unless you have
>    specific licensing/distribution plans for the MSDK code.
>
> will do, honestly forgot about it

>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msdk/msdk/pull/7#issuecomment-91093227>.
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Comment by berlinguyinca** [comment]
In general I think thats a great idea for specifications of interfaces and
default solutions. But would like to keep some concrete implementations in
there own modules.

For example, people should not have to include MoNA and all it's dependency
(jackson, etc) in there project by default, only if they actually utilize
the functionality. This will also help avoid version conflicts in the long
run.

So let's move the msdk-query to msdk-identification, but leave msdk-mona as
a sub module? Kinda like the CDK does it? At some point I would also like
to add a BinBase (would be very heavy, no real REST api) Identification
package and an Amdis implementation for raw datafiles.


On Wed, Apr 8, 2015 at 7:22 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> Another topic for consideration: I think if we create a new maven project
> for each MSDK module, we will end up having too many maven projects with
> lots of maintenance overhead. My idea is to create a maven project for each
> group of functions, e.g.
> msdk-io for data reading/writing modules
> msdk-featuredetection for feature detection algoritms
> msdk-identification for identification algorithms
>
> In that sense, the msdk-mona and msdk-query could be moved to
> msdk-identification. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msdk/msdk/pull/7#issuecomment-91094103>.
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Comment by tomas-pluskal** [comment]
Ok let's keep MoNA as a separate package for now. As for msdk-query, it can go to msdk-identification or even to msdk-interfaces (why not?).

**Comment by berlinguyinca** [comment]
yeah please by all means. This sounds good.

On Thu, Apr 9, 2015 at 5:54 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> Ok let's keep MoNA as a separate package for now. As for msdk-query, it
> can go to msdk-identification or even to msdk-interfaces (why not?).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msdk/msdk/pull/7#issuecomment-91391428>.
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Pull request merged**
