### PR TITLE
MSDK update to 0.0.3-SNAPSHOT

### PR DESCRIPTION
**Pull request by tomas-pluskal**

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Nils @nilshoffmann, 
I reverted your recent changes to pom.xml, because I could not get the mvn:release plugin to work and successfully deploy the artifacts to the Sonatype repository. If you provide a working configuration, I will be happy to use it, but for now I am going to stick to the current pom.xml, which works.

**Comment by nilshoffmann** [comment]
Hi Tomaš,
do you have the output of the release plugin available so that I can check what went wrong, please? 

Best regards, Nils

----- Reply message -----
Von: "Tomáš Pluskal" <notifications@github.com>
An: "msdk/msdk" <msdk@noreply.github.com>
Cc: "Nils Hoffmann" <nhoffmann@netbeans.org>
Betreff: [msdk] MSDK update to 0.0.3-SNAPSHOT (#62)
Datum: Mo., Dez. 14, 2015 20:58

Nils @nilshoffmann, 

I reverted your recent changes to pom.xml, because I could not get the mvn:release plugin to work and successfully deploy the artifacts to the Sonatype repository. If you provide a working configuration, I will be happy to use it, but for now I am going to stick to the current pom.xml, which works.

&mdash;

**Comment by dyrlund** [comment]
It seems that this pull request is a duplicate of the commits in #63.

**Comment by tomas-pluskal** [comment]
Hi Nils,

I think the best way to debug this is if you try to perform a release by yourself. Once you get a working configuration, we can add it to the pom.xml

In order to make a release, you need to have a Sonatype JIRA account: https://issues.sonatype.org/secure/Signup!default.jspa
Please let me know your username once you create the account. I will add your user to the MSDK project.

**Comment by nilshoffmann** [comment]
@tomas-pluskal I checked the BUILD.md documentation and if that is the way that the release is being performed, it is clear why my change did not work: the profile is only activated if a specific property is set. This is normally done by the maven-release-plugin during the release:prepare and release:perform phases (activation section of the profile), but if the release is performed manually without the plugin, the release profile (which is completely independent of the release plugin btw.) needs to be activated using the -Pmsdk-release switch.

**Comment by tomas-pluskal** [comment]
Hi Nils,

Please try to make one release (v. 0.0.3) using your release profile configuration. If your jars successfully appear in Maven Central, I am happy to adopt the configuration you created.

Tomas

**Pull request merged**
