### PR TITLE
Working on feature table alignment based on m/z and RT

### PR DESCRIPTION
**Pull request by dyrlund**

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
I'm going to merge this, but we should synchronize the effort with Sandra @SandraCastilloPriego , I think she was going to work on the join aligner, too.

**Comment by dyrlund** [comment]
I agree. Currently I'm tracking what I'm working on though the issues on [MZmine 3](https://github.com/mzmine/mzmine3/issues) but we should maybe do the same here?

**Comment by SandraCastilloPriego** [comment]
Hi,

yes, I was working on the join aligner and it was almost finished..

2015-12-18 16:41 GMT+02:00 Thomas F. Dyrlund <notifications@github.com>:

**Comment by dyrlund** [comment]
I'm sorry to hear that. To prevent this issue going forward, I suggest that we use the issue tracking on GitHub and assign ourselves to issues once we start working on them. That way we can easier coordinate our work.

**Pull request merged**
