### PR TITLE
CWT test case is now able to read the data from mzml rawdata file.

### PR DESCRIPTION
**Pull request by dharak029**

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
It seems there is some compilation issue with the last commit

**Comment by dharak029** [comment]
In my eclipse it's showing the build is successful. I tried several times. What should I do?

**Comment by tomas-pluskal** [comment]
There is one missing }

**Comment by tomas-pluskal** [comment]
This block is not closed:
````
		catch(IOException e){
		System.out.print("problem in writing output.txt");
		writer.close();
````

**Comment by dharak029** [comment]
There's some problem in commit. I'm seeing extra code in test file. I removed that code.

**Comment by dharak029** [comment]
I'm not able to push the changes correctly.

**Comment by tomas-pluskal** [comment]
I made some changes to MsSpectrum. If you pulled the recent commits to the main repo, you should see some errors in Eclipse.

**Comment by tomas-pluskal** [comment]
[ERROR] /home/travis/build/msdk/msdk/msdk-featdet/msdk-featdet-ADAP-3D/src/test/java/io/github/msdk/featdet/ADAP3D/common/algorithms/ContinuousWaveletTransformTest.java:[66,40] method getMzValues in interface io.github.msdk.datamodel.msspectra.MsSpectrum cannot be applied to given types;
[ERROR] required: no arguments
[ERROR] found: double[]

**Comment by tomas-pluskal** [comment]
Do you see that?

**Comment by dharak029** [comment]
I have not pulled the recent commits to fork my branch. Let me pull that.

**Comment by tomas-pluskal** [comment]
You need to make a few minor updates to your code, otherwise it won't compile.
````
mzBuffer = scan.getMzValues(mzBuffer);
````
has to be changed to 
````
mzBuffer = scan.getMzValues();
````
Don't you see any errors in Eclipse?

**Comment by dharak029** [comment]
I'm not able to pull the changes in my fork branch. Let me close this pull request and I'll create new one after pulling latest code.

**Pull request closed without merging**
